import { Handshake } from "../models/Handshake";
export const globalState = {
  navigation: null,
  timer: 0,
  setTimer: function () {},
  hasShakeStarted: false,
  setHasShakeStarted: function () {},
  hasShakeEnded: false,
  setHasShakeEnded: function () {},
  selectedHandshake: new Handshake(),
  setSelectedHandshake: function () {},
  selectedPersonHandshake: new Handshake(),
  setSelectedPersonHandshake: function () {},
  playerHandshakeAnimation: { values: {} },
  personHandshakeAnimation: { values: {} },
  dispatch: function () {},
  showWalkthrough: false,
  startWalkthrough: function () {},
  modalVisible: false,
  showModal: function () {},
};
export const nGlobalState = {
  navigation: "navigation",
  timer: "timer",
  setTimer: "setTimer",
  hasShakeStarted: "hasShakeStarted",
  setHasShakeStarted: "setHasShakeStarted",
  hasShakeEnded: "hasShakeEnded",
  setHasShakeEnded: "setHasShakeEnded",
  selectedHandshake: "selectedHandshake",
  setSelectedHandshake: "setSelectedHandshake",
  selectedPersonHandshake: "selectedPersonHandshake",
  setSelectedPersonHandshake: "setSelectedPersonHandshake",
  playerHandshakeAnimation: "playerHandshakeAnimation",
  personHandshakeAnimation: "personHandshakeAnimation",
  dispatch: "dispatch",
  showWalkthrough: "showWalkthrough",
  startWalkthrough: "startWalkthrough",
  modalVisible: "modalVisible",
  showModal: "showModal",
};
